import type { Client, Opportunity, Interaction, Task } from '@/lib/types';
import { subDays, format } from 'date-fns';

const now = new Date();

export const clients: Client[] = [
  {
    id: 'CLI-001',
    companyName: 'Innovate Inc.',
    contactPerson: 'Alice Johnson',
    phone: '123-456-7890',
    email: 'alice.j@innovate.com',
    address: '123 Tech Park, Silicon Valley, CA',
    industry: 'Technology',
    status: 'active',
    type: 'customer',
    createdAt: format(subDays(now, 150), 'yyyy-MM-dd'),
  },
  {
    id: 'CLI-002',
    companyName: 'Quantum Solutions',
    contactPerson: 'Bob Williams',
    phone: '234-567-8901',
    email: 'bob.w@quantum.com',
    address: '456 Innovation Dr, Boston, MA',
    industry: 'Consulting',
    status: 'active',
    type: 'prospect',
    createdAt: format(subDays(now, 60), 'yyyy-MM-dd'),
  },
  {
    id: 'CLI-003',
    companyName: 'Apex Logistics',
    contactPerson: 'Charlie Brown',
    phone: '345-678-9012',
    email: 'charlie.b@apex.com',
    address: '789 Supply Chain, Chicago, IL',
    industry: 'Logistics',
    status: 'active',
    type: 'lead',
    createdAt: format(subDays(now, 15), 'yyyy-MM-dd'),
  },
  {
    id: 'CLI-004',
    companyName: 'Starlight Media',
    contactPerson: 'Diana Prince',
    phone: '456-789-0123',
    email: 'diana.p@starlight.com',
    address: '101 Hollywood Blvd, Los Angeles, CA',
    industry: 'Media',
    status: 'inactive',
    type: 'customer',
    createdAt: format(subDays(now, 300), 'yyyy-MM-dd'),
  },
    {
    id: 'CLI-005',
    companyName: 'Healthwell Corp',
    contactPerson: 'Ethan Hunt',
    phone: '567-890-1234',
    email: 'ethan.h@healthwell.com',
    address: '21 Cure Lane, Philadelphia, PA',
    industry: 'Healthcare',
    status: 'active',
    type: 'prospect',
    createdAt: format(subDays(now, 45), 'yyyy-MM-dd'),
  },
];

export const opportunities: Opportunity[] = [
  {
    id: 'OPP-001',
    clientId: 'CLI-002',
    stage: 'proposal',
    value: 50000,
    closingDate: format(new Date(now.getFullYear(), now.getMonth() + 1, 15), 'yyyy-MM-dd'),
    client: clients[1],
  },
  {
    id: 'OPP-002',
    clientId: 'CLI-003',
    stage: 'prospecting',
    value: 75000,
    closingDate: format(new Date(now.getFullYear(), now.getMonth() + 2, 20), 'yyyy-MM-dd'),
    client: clients[2],
  },
  {
    id: 'OPP-003',
    clientId: 'CLI-001',
    stage: 'won',
    value: 120000,
    closingDate: format(subDays(now, 30), 'yyyy-MM-dd'),
    client: clients[0],
  },
  {
    id: 'OPP-004',
    clientId: 'CLI-005',
    stage: 'negotiation',
    value: 95000,
    closingDate: format(new Date(now.getFullYear(), now.getMonth(), 28), 'yyyy-MM-dd'),
    client: clients[4],
  },
    {
    id: 'OPP-005',
    clientId: 'CLI-004',
    stage: 'lost',
    value: 30000,
    closingDate: format(subDays(now, 90), 'yyyy-MM-dd'),
    client: clients[3],
  },
];

export const interactions: Interaction[] = [
  {
    id: 'INT-001',
    clientId: 'CLI-001',
    type: 'email',
    notes: 'Sent follow-up email regarding new feature set.',
    salesperson: 'Jane Doe',
    date: format(subDays(now, 2), 'yyyy-MM-dd'),
    client: clients[0],
  },
  {
    id: 'INT-002',
    clientId: 'CLI-002',
    type: 'call',
    notes: 'Initial discovery call. Client is interested in Quantum Solutions.',
    salesperson: 'John Smith',
    date: format(subDays(now, 7), 'yyyy-MM-dd'),
     client: clients[1],
  },
  {
    id: 'INT-003',
    clientId: 'CLI-002',
    type: 'demo',
    notes: 'Product demo completed. They were impressed with the features.',
    salesperson: 'John Smith',
    date: format(subDays(now, 1), 'yyyy-MM-dd'),
     client: clients[1],
  },
  {
    id: 'INT-004',
    clientId: 'CLI-003',
    type: 'meeting',
    notes: 'Met with stakeholders to discuss logistics challenges.',
    salesperson: 'Jane Doe',
    date: format(subDays(now, 5), 'yyyy-MM-dd'),
     client: clients[2],
  },
];

export const tasks: Task[] = [
  {
    id: 'TSK-001',
    clientId: 'CLI-002',
    title: 'Prepare proposal for Quantum Solutions',
    dueDate: format(new Date(now.getFullYear(), now.getMonth(), now.getDate() + 3), 'yyyy-MM-dd'),
    assignedTo: 'John Smith',
    completed: false,
    client: clients[1],
  },
  {
    id: 'TSK-002',
    clientId: 'CLI-003',
    title: 'Follow up with Charlie Brown',
    dueDate: format(new Date(now.getFullYear(), now.getMonth(), now.getDate()), 'yyyy-MM-dd'),
    assignedTo: 'Jane Doe',
    completed: false,
    client: clients[2],
  },
  {
    id: 'TSK-003',
    clientId: 'CLI-001',
    title: 'Schedule Q3 check-in',
    dueDate: format(new Date(now.getFullYear(), now.getMonth(), now.getDate() + 10), 'yyyy-MM-dd'),
    assignedTo: 'Jane Doe',
    completed: false,
    client: clients[0],
  },
  {
    id: 'TSK-004',
    clientId: null,
    title: 'Update sales playbook',
    dueDate: format(new Date(now.getFullYear(), now.getMonth(), now.getDate() + 5), 'yyyy-MM-dd'),
    assignedTo: 'Admin',
    completed: true,
    client: null,
  },
  {
    id: 'TSK-005',
    clientId: 'CLI-002',
    title: 'Send demo recording to Bob Williams',
    dueDate: format(new Date(now.getFullYear(), now.getDate() - 1), 'yyyy-MM-dd'),
    assignedTo: 'John Smith',
    completed: true,
    client: clients[1],
  },
];
