import type { Client, Opportunity, Interaction, Task } from '@/lib/types';
import { subDays, format } from 'date-fns';

const now = new Date();

export const clients: Client[] = [
  {
    id: 'CLI-001',
    companyName: 'Inovacije d.o.o.',
    contactPerson: 'Ana Horvat',
    phone: '123-456-7890',
    email: 'ana.h@inovacije.com',
    address: 'Tehnološki park 123, Zagreb',
    industry: 'Tehnologija',
    status: 'active',
    type: 'customer',
    createdAt: format(subDays(now, 150), 'yyyy-MM-dd'),
  },
  {
    id: 'CLI-002',
    companyName: 'Kvantna Rješenja',
    contactPerson: 'Borna Kovač',
    phone: '234-567-8901',
    email: 'borna.k@kvantna.com',
    address: 'Inovacijska cesta 456, Split',
    industry: 'Konzalting',
    status: 'active',
    type: 'prospect',
    createdAt: format(subDays(now, 60), 'yyyy-MM-dd'),
  },
  {
    id: 'CLI-003',
    companyName: 'Apex Logistika',
    contactPerson: 'Karlo Babić',
    phone: '345-678-9012',
    email: 'karlo.b@apex.com',
    address: 'Lanac opskrbe 789, Rijeka',
    industry: 'Logistika',
    status: 'active',
    type: 'lead',
    createdAt: format(subDays(now, 15), 'yyyy-MM-dd'),
  },
  {
    id: 'CLI-004',
    companyName: 'Starlight Media',
    contactPerson: 'Dijana Princeza',
    phone: '456-789-0123',
    email: 'dijana.p@starlight.com',
    address: 'Hollywoodski Bulevar 101, Osijek',
    industry: 'Mediji',
    status: 'inactive',
    type: 'customer',
    createdAt: format(subDays(now, 300), 'yyyy-MM-dd'),
  },
    {
    id: 'CLI-005',
    companyName: 'Zdravlje d.o.o.',
    contactPerson: 'Igor Horvat',
    phone: '567-890-1234',
    email: 'igor.h@zdravlje.com',
    address: 'Ulica Lijekova 21, Zadar',
    industry: 'Zdravstvo',
    status: 'active',
    type: 'prospect',
    createdAt: format(subDays(now, 45), 'yyyy-MM-dd'),
  },
];

export const opportunities: Opportunity[] = [
  {
    id: 'OPP-001',
    clientId: 'CLI-002',
    stage: 'proposal',
    value: 50000,
    closingDate: format(new Date(now.getFullYear(), now.getMonth() + 1, 15), 'yyyy-MM-dd'),
    client: clients[1],
  },
  {
    id: 'OPP-002',
    clientId: 'CLI-003',
    stage: 'prospecting',
    value: 75000,
    closingDate: format(new Date(now.getFullYear(), now.getMonth() + 2, 20), 'yyyy-MM-dd'),
    client: clients[2],
  },
  {
    id: 'OPP-003',
    clientId: 'CLI-001',
    stage: 'won',
    value: 120000,
    closingDate: format(subDays(now, 30), 'yyyy-MM-dd'),
    client: clients[0],
  },
  {
    id: 'OPP-004',
    clientId: 'CLI-005',
    stage: 'negotiation',
    value: 95000,
    closingDate: format(new Date(now.getFullYear(), now.getMonth(), 28), 'yyyy-MM-dd'),
    client: clients[4],
  },
    {
    id: 'OPP-005',
    clientId: 'CLI-004',
    stage: 'lost',
    value: 30000,
    closingDate: format(subDays(now, 90), 'yyyy-MM-dd'),
    client: clients[3],
  },
];

export const interactions: Interaction[] = [
  {
    id: 'INT-001',
    clientId: 'CLI-001',
    type: 'email',
    notes: 'Poslan je follow-up email u vezi novih značajki.',
    salesperson: 'Iva Ivić',
    date: format(subDays(now, 2), 'yyyy-MM-dd'),
    client: clients[0],
  },
  {
    id: 'INT-002',
    clientId: 'CLI-002',
    type: 'call',
    notes: 'Inicijalni poziv. Klijent je zainteresiran za Kvantna Rješenja.',
    salesperson: 'Pero Perić',
    date: format(subDays(now, 7), 'yyyy-MM-dd'),
     client: clients[1],
  },
  {
    id: 'INT-003',
    clientId: 'CLI-002',
    type: 'demo',
    notes: 'Prezentacija proizvoda je završena. Bili su impresionirani značajkama.',
    salesperson: 'Pero Perić',
    date: format(subDays(now, 1), 'yyyy-MM-dd'),
     client: clients[1],
  },
  {
    id: 'INT-004',
    clientId: 'CLI-003',
    type: 'meeting',
    notes: 'Sastanak s dionicima radi razgovora o logističkim izazovima.',
    salesperson: 'Iva Ivić',
    date: format(subDays(now, 5), 'yyyy-MM-dd'),
     client: clients[2],
  },
];

export const tasks: Task[] = [
  {
    id: 'TSK-001',
    clientId: 'CLI-002',
    title: 'Pripremiti ponudu za Kvantna Rješenja',
    dueDate: format(new Date(now.getFullYear(), now.getMonth(), now.getDate() + 3), 'yyyy-MM-dd'),
    assignedTo: 'Pero Perić',
    completed: false,
    timeEstimate: 5,
    client: clients[1],
  },
  {
    id: 'TSK-002',
    clientId: 'CLI-003',
    title: 'Kontaktirati Karla Babića',
    dueDate: format(new Date(now.getFullYear(), now.getMonth(), now.getDate()), 'yyyy-MM-dd'),
    assignedTo: 'Iva Ivić',
    completed: false,
    timeEstimate: 1,
    client: clients[2],
  },
  {
    id: 'TSK-003',
    clientId: 'CLI-001',
    title: 'Zakazati Q3 provjeru',
    dueDate: format(new Date(now.getFullYear(), now.getMonth(), now.getDate() + 10), 'yyyy-MM-dd'),
    assignedTo: 'Iva Ivić',
    completed: false,
    timeEstimate: 2,
    client: clients[0],
  },
  {
    id: 'TSK-004',
    clientId: null,
    title: 'Ažurirati prodajnu strategiju',
    dueDate: format(new Date(now.getFullYear(), now.getMonth(), now.getDate() + 5), 'yyyy-MM-dd'),
    assignedTo: 'Admin',
    completed: true,
    timeEstimate: 8,
    client: null,
  },
  {
    id: 'TSK-005',
    clientId: 'CLI-002',
    title: 'Poslati snimku prezentacije Borni Kovaču',
    dueDate: format(new Date(now.getFullYear(), now.getDate() - 1), 'yyyy-MM-dd'),
    assignedTo: 'Pero Perić',
    completed: true,
    timeEstimate: 0.5,
    client: clients[1],
  },
];
