
"use client";

import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { Button } from "@/components/ui/button";
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Save } from "lucide-react";
import { useLanguage } from "@/context/language-context";
import { useToast } from "@/hooks/use-toast";
import { useAuth } from "@/context/auth-context";

/**
 * Interface for the props of the AddUserForm component.
 * @property {() => void} onUserAdded - Callback function to be executed when a user is successfully added.
 */
interface AddUserFormProps {
    onUserAdded: () => void;
}

/**
 * A form component for adding new users to the system.
 * It handles form validation and submission.
 * @param {AddUserFormProps} props - The component props.
 * @returns {React.ReactElement} The rendered form.
 */
export function AddUserForm({ onUserAdded }: AddUserFormProps) {
  const { t } = useLanguage();
  const { toast } = useToast();
  const { addUser } = useAuth();

  // Zod schema for form validation
  const userFormSchema = z.object({
    name: z.string().min(2, "Name is required."),
    email: z.string().email("Invalid email address."),
    username: z.string().min(4, "Username must be at least 4 characters."),
    password: z.string().min(6, "Password must be at least 6 characters."),
    role: z.enum(["admin", "user"]),
  });
  
  type UserFormValues = z.infer<typeof userFormSchema>;

  // Initialize react-hook-form
  const form = useForm<UserFormValues>({
    resolver: zodResolver(userFormSchema),
    defaultValues: {
        name: "",
        email: "",
        username: "",
        password: "",
        role: "user",
    },
  });

  /**
   * Handles the form submission.
   * It calls the `addUser` function from the AuthContext and shows a toast notification on success or error.
   * @param {UserFormValues} values - The validated form values.
   */
  async function onSubmit(values: UserFormValues) {
    try {
      await addUser(values.email, values.password, {
        id: '', // ID will be generated by Firebase Auth
        name: values.name,
        username: values.username,
        email: values.email,
        role: values.role,
      });
      onUserAdded(); // Callback to inform parent component
      toast({
          title: t('admin_page.toast_success_title'),
          description: t('admin_page.toast_success_description', { name: values.name }),
      });
      form.reset(); // Reset form fields after successful submission
    } catch (error: any) {
        // Specific error handling for email already in use
        if (error.code === 'auth/email-already-in-use') {
            toast({
                title: "Error: Email already in use",
                description: "This email address is already registered. Please use a different one or delete the existing user from the Firebase Authentication console.",
                variant: "destructive"
            });
        } else {
             // Generic error handling
             toast({
                title: "Error",
                description: "An unexpected error occurred while adding the user.",
                variant: "destructive"
            });
        }
    }
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle>{t('admin_page.form_title')}</CardTitle>
        <CardDescription>
          {t('admin_page.form_description')}
        </CardDescription>
      </CardHeader>
      <CardContent>
        <Form {...form}>
          <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
            <FormField
                control={form.control}
                name="name"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>{t('admin_page.form_name')}</FormLabel>
                    <FormControl>
                      <Input placeholder={t('admin_page.form_name_placeholder')} {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
               <FormField
                control={form.control}
                name="email"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>{t('admin_page.form_email')}</FormLabel>
                    <FormControl>
                      <Input placeholder={t('admin_page.form_email_placeholder')} {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="username"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>{t('admin_page.form_username')}</FormLabel>
                    <FormControl>
                      <Input placeholder={t('admin_page.form_username_placeholder')} {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
               <FormField
                control={form.control}
                name="password"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>{t('admin_page.form_password')}</FormLabel>
                    <FormControl>
                      <Input type="password" {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
               <FormField
                control={form.control}
                name="role"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>{t('admin_page.form_role')}</FormLabel>
                    <Select onValueChange={field.onChange} defaultValue={field.value}>
                      <FormControl>
                        <SelectTrigger>
                          <SelectValue />
                        </SelectTrigger>
                      </FormControl>
                      <SelectContent>
                        <SelectItem value="user">{t('admin_page.form_role_user')}</SelectItem>
                        <SelectItem value="admin">{t('admin_page.form_role_admin')}</SelectItem>
                      </SelectContent>
                    </Select>
                    <FormMessage />
                  </FormItem>
                )}
              />
            <div className="flex justify-end pt-4">
              <Button type="submit">
                <Save className="mr-2 h-4 w-4" />
                {t('admin_page.form_save_button')}
              </Button>
            </div>
          </form>
        </Form>
      </CardContent>
    </Card>
  );
}
